{% set name = "yaqd-ti" %}
{% set version = "2020.12.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/yaqd-ti-{{ version }}.tar.gz
  sha256: a08e10eafddd9ce2350f24ea31a2c71d69871c8f7fb660a5b855317c9a91a3b0

build:
  number: 0
  noarch: python
  entry_points:
    - yaqd-ads1115 = yaqd_ti._ads1115:ADS1115.main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - flit
    - yaqd-core >=2020.06.3
    - smbus2
  run:
    - python >=3.7
    - yaqd-core >=2020.06.3
    - smbus2

test:
  imports:
    - yaqd_ti
  commands:
    - pip check
    - yaqd-ads1115 --help
  requires:
    - pip

about:
  home: https://yaq.fyi
  summary: yaq daemons for interfacing with Texas Instruments integrated circuits
  dev_url: https://gitlab.com/yaq/yaqd-ti
  license: LGPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - untzag
    - ksunden
